### ISSUE TITLE
TemporaryVotepool.sol is not compatible with GNU coding standards 

### ISSUE THREAD

**Issue by yaronvel** [EthereumCommonwealth/Roadmap#20]
Well, even filename is not compatible.
Capital letters should be avoided in most places.

**Comment by Dexaran** [comment]
It is more common to use solidity coding standard for smart-contracts. We have not yet established a new one.

If you will look at Ethereum Foundations' [ENS contracts](https://github.com/ethereum/ens/tree/master/contracts) for example, then you will see similar naming.

I will be happy to discuss a new coding standard for smart-contracts, but it's not a prior target just right now, so I'm following an existing common solidity coding standard yet.

**Comment by yaronvel** [comment]
It is definitely not compatible with [current solidity coding standards](http://solidity.readthedocs.io/en/develop/style-guide.html).

Function name need not be capitalized for example.

**Comment by Dexaran** [comment]
Thanks for the reminder.

I will update `TemporaryVotepool.sol` anyways.
