### ISSUE TITLE
Viper online compiler.

### ISSUE THREAD

**Issue by sgitt-vassky** [EthereumCommonwealth/Roadmap#21]
I've seen that you prefer Viper adoption on Classic rather than solidity promotion. I'd like to recommend to start with creating an analogue of Remix online compiler.

**Comment by yograterol** [comment]
Why Viper over Solidity? I like Python, but which are the reason to prefer Viper? BTW, I am ok with that. So, what could be a MVP to this in features?

**Comment by Dexaran** [comment]
I prefer Viper over Solidity and I fully agree that Viper should be widely adopted.
https://ethereumclassic.github.io/blog/2017-03-13-viper/

>Why Viper over Solidity? 

1. **Readability of the code**. Being a smart-contract auditor I can say that it is the most important point to build fault-tolerant systems. Fault-tolerance is highest prior target for smart-contracts as any error is leading to loss of millions of UDS. Solidity is **very bad language** to create fault-tolerant smart-contracts.

2. General ease of writing unsafe and misleading code in Solidity.

3. Easy accessibility and extensibility of the compiler code.

**Comment by Dexaran** [comment]
https://tproger.ru/news/ieee-spectrum-rating-2017/#ampshare=https://tproger.ru/news/ieee-spectrum-rating-2017/

**Comment by Dexaran** [comment]
We will set up a server for the Viper-compiler and a UI for this server. The code will actually be compiled on the server, and the bytecode will be returned to the UI.

I think this will be an effective solution for the initial stage.

**Comment by yograterol** [comment]
@Dexaran Yes, We will do it as MVP. After we could add more features.

**Comment by Dexaran** [comment]
The first version of Viper compiler is already operational:
https://codepen.io/yograterol/full/aypYjP/

Further updates are coming soon.

**Comment by Dexaran** [comment]
The Vyper compiler is developed: https://codepen.io/yograterol/full/aypYjP/
