### ISSUE TITLE
Cold staking DEX token.

### ISSUE THREAD

**Issue by sgitt-vassky** [EthereumCommonwealth/Roadmap#29]
I've seen that you are closing your ico. The supply of dex token is incredibly low. May be we need to introduce proof of stake coin supply growth? It looks to be possible with erc223.

It would be the first proof of stake erc223 token on ethereum.

**Comment by Dexaran** [comment]
I am sure that it is possible to realize an increase in the balance in proportion to the current balance of the address and passed time.

We are going to update the ERC223 token standard default implementation therefore it may be a good idea to update DEX token contracts as well.

Anyways, I think that we need to launch a vote to decide whether it is needed or not to implement a cold staking supply increase for DEX tokens.

**Comment by Dexaran** [comment]
@sgitt-vassky if you have any proposals then you can always initiate the voting for it. 
Here is a description of the voting process: https://github.com/Dexaran/ICO/issues/1

You can deploy contracts yourself and announce it. If the voting would be ended and the decision will be made to implement it then I will do it without any problems.
