### ISSUE TITLE
New blockchain explorer.

### ISSUE THREAD

**Issue by sgitt-vassky** [EthereumCommonwealth/Roadmap#31]
Gastracker sucks. It is always lagging. It is displaying -2714 confirmations of 12. It doesn't display token transfers. It doesn't display comments and address reputation. It doesn't provide any advanced functionality. It doesn't support testnets.
If you want to unite the whole Ethereum-core project's infrastructure with common services then it's your chance. Common wallet will be CEW. Common extension will be classicmask. We need common blockchain explorer with advanced functionality now.

**Comment by yograterol** [comment]
i agree with you, maybe a better explorer for ETC and Callisto would work, no? cc @Dexaran

**Comment by elaineo** [comment]
@yograterol were you still interested in proposing a new architecture for the existing explorer? if not i will close the issue https://github.com/ethereumproject/explorer/issues/57

**Comment by Dexaran** [comment]
I agree. Blockchain explorer is an essential part of each blockchain-project ecosystem.

Gastracker solves this problem for ETC for long time, but there are some problems with it:

1. **Lack of debugging information.** Etherscan represents transaction/ call info in more convenient form.

2. **Testnet support.** ETC will need it's own testnet. ETH has 3 testnets and they are supported by Etherscan and MEW. ETC doesn't have any.

3. **Scalability.** MEW starts to support custom nodes. I think that creating of a customizable blockchain exlorer that will support multiple chains simultaneously is a good idea.

4. **Common interfaces.** Etherscan displays "ERC20 Transfer" / "ENS Register Name" / "ENS Set Resolver" and other common calls in human-readable form.

5. **Names and tokens.** We need to implement  ECNS/DexNS names support on some blockchain explorer.

Developing a blockchain explorer is a complex and expensive task and I don't really want to build it from scratch. I prefer to make patches to improve gastracker.

**Comment by RorschachRev** [comment]
I will make one soonish. This overlaps with 2 other projects I wanted to do, so making html output isn't that much extra work. Supporting ECNS/DexNS and tokens is probably the only "extra" work but I'll at least make a core.
The system I make will support API query via rest+jsonrpc for wallet whitelisting of addresses. (e.g. HTML view or jsonrpc view, depending on URL)

**Comment by Dexaran** [comment]
https://github.com/EthereumCommonwealth/Roadmap/issues/41
