### ISSUE TITLE
Ethereum messaging system protocol.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Roadmap#36]
The following is a proposal to define a protocol to solve a problem of a complete lack of possibility to communicate with an owner of a certain address on Ethereum CLassic, Ethereum, UBQ, Expanse or PIRL networks.

EIP 802: https://github.com/ethereum/EIPs/issues/802

ECIP 85: https://github.com/ethereumproject/ECIPs/issues/85

**Comment by Lyxur** [comment]
Awesome idea. Lets ICO it.

**Comment by Dexaran** [comment]
@Lyxur how will we ICO a **free** messaging system? And for what purpose?

**Comment by Lyxur** [comment]
Add a rating system. Karma or something like this. Increase rating of the message if sender has tokens on balance. Scarcity and utility of this token will make a good purpose for ICO.

**Comment by Dexaran** [comment]
@Lyxur I think that ICO is not really necessary here and rating system will not be that useful. It's not a messenger or a chat room. It's an emergency opportunity to contact an owner of a certain address without knowing who he is.

**Comment by Lyxur** [comment]
It will not hurt the initial functionality of the system. Even more, it will be a token with a real use case unlike many others. If someone does not want to use tokens and rating, then he will not use it. It may be optional.

**Comment by Dexaran** [comment]
I see you are really hell bent in ICOing the message service. Well, let's resolve it with a DEX token voting.

**Comment by Lyxur** [comment]
Do I need to create a new issue here?

**Comment by Dexaran** [comment]
No need to create it right now. I think that we must resolve this first: https://github.com/ethereum/EIPs/issues/802#issuecomment-353898633

**Comment by Dexaran** [comment]
Deployed on ETC chain: https://www.reddit.com/r/EthereumClassic/comments/7n2a83/addresstoaddress_message_system_based_on/
