### ISSUE TITLE
DexNS final launch.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Roadmap#37]
DexNS, the first crosschain decentralized naming service for human-readable address resolutions and token-related services scalability improvement tool, has successfully passed the bug bounty and final changes were applied.

[DexNS bug bounty reference](https://github.com/EthereumCommonwealth/Roadmap/issues/33).

[DexNS final version reference](https://github.com/EthereumCommonwealth/DexNS).

DexNS contracts are currently deployed on ETC mainnet. We are transferring names from the trial version now. Service will be officially announced at 25 Dec, 2017.

A final service will take a fee of 0,01 ETC per Name to resolve DDOS issues. All the fee funds would be distributed according to the [Ethereum Commonwealth revenue distribution process](https://github.com/EthereumCommonwealth/Roadmap/issues/24).

**Comment by clshack** [comment]
I am following 💃

**Comment by dalmat89** [comment]
let's go!

**Comment by Dexaran** [comment]
Launched: https://www.reddit.com/r/EthereumClassic/comments/7m1cj9/ethereum_commonwealth_announces_dexns_is_finally/
