### ISSUE TITLE
MAJOR DROP in gas cost, who will lead Ethereum Classic into the new blockchain?

### ISSUE THREAD

**Issue by hyvmind** [EthereumCommonwealth/Roadmap#39]
As more and more updates to ETH (Ethereum) come out and additional capabilities in the blockchain are developed, who will maintain the code of the ETC chain? Will ETC move to a Proof of Stake model as well?

**Comment by Dexaran** [comment]
There are three ETC development teams. [ETCDEV](https://www.etcdevteam.com/), [IOHK](https://iohk.io/) and [Ethereum Commonwealth](https://github.com/EthereumCommonwealth).

The ETC protocol is an abstract set of rules that determine the capabilities of this blockchain. The client implements this set of rules. To be honest, this doesn't matter what exactly language did you used to implement it. There are three ETC clients: Geth, Parity and Daedalus. Geth and Parity are maintained by ETCDEV, Daedalus is maintained by IOHK. Currently, Ethereum Commonwaelth is restoring compatibility of Geth-classic and Ethereum Foundation's Geth: https://github.com/EthereumCommonwealth/geth-classic.

Ethereum Commonwaelth is maintaining the infrastructure of ETC.
