### ISSUE TITLE
Blockchain explorer development.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Roadmap#41]
## Requirements

The blockchain explorer is intended to:

- [ ] Display blocks, transactions, state of addresses and provide the rest of default blockchain functionality.

- [ ] Ensure the easy addition of new networks compatible with the ETC. It is planned to support ETC, ETH, UBQ, EXP, PIRL, Rinkeby (testnet), Kovan (testnet), Morden (testnet), Ropsten (testnet), Callisto-test (testnet), Callisto chains simultaneously.

- [ ] Display a full history of transactions of the given address.

- [ ] Display DexNS names of addresses at any network.

- [ ] Properly display the signatures of known events: `Transfer`, bidding ENS events, `NewMessage` of messaging contract ( #36 ), `Transfer` of ERC223, ICO events of token mint and so on.

- [ ] Ensure the easy addition of new known events signatures.

- [ ] Get a history of messages of a given address by Messaging Smart-contract of ETC network: #36 

- [ ] Properly display internal contract invocations.

## Callisto (optional)

- [ ] Display "amount at stake" at Callisto network (CLO only)

- [ ] Display "current staking amount" at Callisto network (CLO only)

## Resolution

https://github.com/EthereumCommonwealth/Galileo

**Comment by yograterol** [comment]
The roadmap for the MVP is there https://github.com/EthereumCommonwealth/Galileo/projects/1

**Comment by dardanlatifi** [comment]
Hi gyes, any update on launching the test net?

**Comment by dardanlatifi** [comment]
Hi guys, any update for the test net? when are you planning to launch it ?

**Comment by AndrewGuarda** [comment]
Hey! Do you have plans to realize public API for blockexplorer?

**Comment by yograterol** [comment]
@AndrewGuarda the block explorer is/will be open source.
