### ISSUE TITLE
rg070

### ISSUE THREAD

**Issue by rg070** [EthereumCommonwealth/Roadmap#47]
good afternoon . I save etc on the classicEtherwallet purse in order to get Callistro but I did not receive Callisto. tell me please when I see Callistro on my wallet?

**Comment by StefanOpariuc** [comment]
Also, the token is not found on classicEtherWallet

**Comment by Dexaran** [comment]
You will receive Callisto at the moment of mainnet launch.
Snapshot is taken at `5 500 000` block. You can now move your ETC and it will not affect the snapshot.

Callisto mainnet launch is scheduled to the end of March.
