### ISSUE TITLE
Idavoll HF #1 - 2020

### ISSUE THREAD

**Issue by yograterol** [EthereumCommonwealth/Roadmap#63]
# Motivation

Following the development of the Callisto Network and the whitepaper goals (https://whitepaper.callisto.network/), Callisto Team introduces changes to Callisto blockchain to take a big step forward in the development of the project.

With this HF, Callisto Team delivers the last promises from the whitepaper, giving more power to the community to choose the future of the project and next steps in the long term growth path. Additionally, Callisto Blockchain will be up to date with the latest changes introduced in Ethereum blockchain, bringing the holders more security in the chain.

# Specification

## Istanbul implementation

Following Ethereum development, in the next Callisto HF we will introduce the next EIPs:

- [EIP-152](https://github.com/ethereum/EIPs/pull/2129): Blake2 compression function F precompile
- [EIP-1108](https://eips.ethereum.org/EIPS/eip-1108): Reduce alt_bn128 precompile gas costs
- [EIP-1344](https://eips.ethereum.org/EIPS/eip-1344): ChainID opcode
- [EIP-1884](https://eips.ethereum.org/EIPS/eip-1884): Repricing for trie-size-dependent opcodes
- [EIP-2028](https://eips.ethereum.org/EIPS/eip-2028): Calldata gas cost reduction
- [EIP-2200](https://github.com/ethereum/EIPs/pull/2200): Rebalance net-metered SSTORE gas cost

## Cold Staking v2

Cold Staking V1 has been working well, and around 58% of CLO supply is currently in the [actual smart-contract](https://explorer2.callisto.network/addr/0xd813419749b3c2cdc94a2f9cfcf154113264a9d6). Through the update of the smart contract we will introduce some changes explained in this paper: https://drive.google.com/file/d/1fFtuQctoLtyEP-Lwlnt2x5pOuVWzZjn4/view

The cold staking update is necessary to proceed with the governance system.

Source code: https://github.com/EthereumCommonwealth/Cold-staking/tree/RideSolo_linear_formula

## Governance System

From the whitepaper, we introduced a governance system that allows the Callisto community to manage the distribution of Callisto Treasury funds.

Source code: https://github.com/EthereumCommonwealth/Governance-System

# Implementation

- Modify Geth and Parity to activate Istanbul HF at Callisto HF.
- Modify Geth and Parity to change the distribution staking reward from the current Cold Staking address to the next Cold Staking v2 address.

* At block 4,950,000, the client will activate all changes proposed in Istanbul HF.

**Comment by RideSolo** [comment]
Very excited to see my staking proposal accepted by callisto :)
