### ISSUE TITLE
Port of MetaMask for Ethereum CLassic.

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Roadmap#8]

**Comment by yograterol** [comment]
I am watching the PR that adds the port to ETC, what do you propose? A fork? 

The current team of MetaMask don't want merge the PR :(

**Comment by Dexaran** [comment]
I'm proposing to make a fork (CLassic Mask). @18dew is currently working on it. It takes too long to merge a PR. If they will decide to merge it in future then we can remove our CLassic Mask and start to contribute to MetaMask development together.

**Comment by yograterol** [comment]
Cool, where are you working it?

**Comment by 18dew** [comment]
Hi, 

I am trying to understand the structure of Metamask and then merging ETC logic on to it...

**Comment by yograterol** [comment]
@18dew hi, :) oh, I got it, do you need help?

**Comment by 18dew** [comment]
Once i upload the code by Sunday would need some help in testing ...

**Comment by Dexaran** [comment]
@18dew please, fork [this repo[(https://github.com/Dexaran/ClassicMask) from me and work here.

**Comment by yograterol** [comment]
@18dew @Dexaran Yes, IMHO create a workflow would be healthy to testing early and check code, make regular commits would be better. What do you think? and create a project in that repo. 

@Dexaran may be, create a organization?

**Comment by Dexaran** [comment]
I will think about creating an organization later. I think that we can work in my repo now and move it to organization later if we decide to do it.

**Comment by yograterol** [comment]
ClassicMask is launched https://github.com/Dexaran/ClassicMask/tree/dist 🚀

**Comment by Dexaran** [comment]
The next step will be to add extensions to [chrome web store](https://chrome.google.com/webstore/category/extensions?hl=en-US), [mozilla add-ons](https://addons.mozilla.org/en-US/firefox/) and so on.

**Comment by yograterol** [comment]
https://addons.mozilla.org/en-US/firefox/addon/classicmask-beta/?src=search
